TICKET_STATUS_OPEN = "open"
TICKET_STATUS_BLOCKED = "blocked"
TICKET_STATUS_ACTIVE = "active"
TICKET_STATUS_CLOSED = "closed"

TICKET_STATUS_CHOICES = (
    (TICKET_STATUS_OPEN, "Open"),
    (TICKET_STATUS_BLOCKED, "Blocked"),
    (TICKET_STATUS_ACTIVE, "Active"),
    (TICKET_STATUS_CLOSED, "Closed"),
)

TICKET_MODULE_NONE = "none"
TICKET_MODULE_SELLER_MATCH = "sellermatch"
TICKET_MODULE_CALCULATOR = "calculator"

TICKET_MODULE_CHOICES = (
    (TICKET_MODULE_NONE, None),
    (TICKET_MODULE_SELLER_MATCH, "Seller Match"),
    (TICKET_MODULE_CALCULATOR, "Calculator"),
)

# ==================
# SLACK APP SETTINGS
# ==================

SLACK_REACTION_OPEN = "white_circle"
SLACK_REACTION_BLOCKED = "red_circle"
SLACK_REACTION_ACTIVE = "computer"
SLACK_REACTION_CLOSED = "white_check_mark"

SLACK_STATUS_REACTION = {
    TICKET_STATUS_OPEN: SLACK_REACTION_OPEN,
    TICKET_STATUS_BLOCKED: SLACK_REACTION_BLOCKED,
    TICKET_STATUS_ACTIVE: SLACK_REACTION_ACTIVE,
    TICKET_STATUS_CLOSED: SLACK_REACTION_CLOSED,
}
