# Generated by Django 5.2.4 on 2025-07-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoreSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "trello_api_key",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Trello API key"),
                ),
                (
                    "trello_api_token",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Trello API token"),
                ),
                (
                    "trello_list_id",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Trello channel"),
                ),
                ("slack_token", models.CharField(blank=True, max_length=255, null=True, verbose_name="Slack token")),
                (
                    "slack_channel_id",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Slack channel"),
                ),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
    ]
