# Generated by Django 5.2.4 on 2025-07-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="trello_board_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Trello board ID"),
        ),
        migrations.AlterField(
            model_name="coresettings",
            name="trello_list_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Trello list ID"),
        ),
    ]
