# Generated by Django 5.2.4 on 2025-07-18 14:33

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrelloLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('module', models.CharField(blank=True, choices=[('none', None), ('sellermatch', 'Seller Match'), ('calculator', 'Calculator')], max_length=100, null=True, verbose_name='Module')),
                ('trello_label_id', models.CharField(blank=True, max_length=45, null=True, verbose_name='Trello label ID')),
                ('trello_label_color', models.CharField(blank=True, max_length=45, null=True, verbose_name='Trello label color')),
                ('trello_label_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='Trello label name')),
            ],
            options={
                'verbose_name': 'Trello Label',
                'verbose_name_plural': 'Trello Labels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('draft', models.BooleanField(default=True)),
                ('ticket_no', models.CharField(default='', max_length=45, verbose_name='Ticket No.')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('module', models.CharField(choices=[('none', None), ('sellermatch', 'Seller Match'), ('calculator', 'Calculator')], default='none', max_length=100, verbose_name='Module')),
                ('status', models.CharField(choices=[('open', 'Open'), ('blocked', 'Blocked'), ('active', 'Active'), ('closed', 'Closed')], default='open', max_length=100, verbose_name='Status')),
                ('last_joblog_log', models.TextField(blank=True, null=True, verbose_name='Last Job Log')),
                ('last_joblog_message', models.TextField(blank=True, null=True, verbose_name='Last Job Log Message')),
                ('last_joblog_stacktrace', models.TextField(blank=True, null=True, verbose_name='Last Job Log Stacktrace')),
                ('trello_ticket_created', models.BooleanField(default=False, verbose_name='Trello Ticket Created')),
                ('trello_ticket_id', models.CharField(blank=True, max_length=45, null=True, verbose_name='Trello Ticket ID')),
                ('trello_ticket_url', models.URLField(blank=True, null=True, verbose_name='Trello Ticket URL')),
                ('slack_notification_sent', models.BooleanField(default=False, verbose_name='Slack Notification Sent')),
                ('slack_message_ts', models.CharField(blank=True, max_length=45, null=True, verbose_name='Slack Message TS')),
                ('slack_channel_id', models.CharField(blank=True, max_length=45, null=True, verbose_name='Slack Channel ID')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assignee', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_author', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='clients.client')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
